config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'welcomes#index'

  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stocks', to: 'stocks#search'

  resources :user_stocks, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord

  has_and_belongs_to_many :users

  scope :alphabetical, -> { order(:name, :ticker) }
  scope :by_ticker, -> (ticker_sym) { where(ticker: ticker_sym) }
 
  def self.new_from_lookup(ticker_symbol)
    begin
      client = IEX::Api::Client.new(publishable_token: 'sk_928f6103385e4fc1a2f4cdb3afd325c9')
      looked_up_stock = client.quote(ticker_symbol)
      new(  #This new is the same that Stock.new() because this is a class method
        name: looked_up_stock.company_name,
        ticker: looked_up_stock.symbol,
        last_price: looked_up_stock.latest_price
      )
    rescue Exception => e
      return nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  MAX_STOCKS_PER_USER = 10

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :stocks

  def stock_already_added?(ticker_sym)
    stock = Stock.by_ticker(ticker_sym).first
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < MAX_STOCKS_PER_USER
  end

  def can_add_stock?(ticker_sym)
    under_stock_limit? && !stock_already_added?(ticker_sym)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_from_lookup(params[:stock])
      flash.now[:alert] = 'You have entered an incorrect symbol.' unless @stock
    else
        flash.now[:alert] = 'You have entered an empty search string.'
    end
    respond_to do |format|
      format.js { render partial: 'users/result' }
    end 
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.by_ticker(params[:stock_ticker]).first

    redirect_to my_portfolio_path, alert: 'You already has this stock.' if current_user.stocks.include?(stock)
    
    if stock.blank?
      stock = Stock.new_from_lookup(params[:stock_ticker])
      stock.save
    end
    current_user.stocks << stock
    redirect_to my_portfolio_path, notice: "#{stock.name} was successfully added to yours stocks."
  end

  def destroy
    stock = Stock.find(params[:id])
    current_user.stocks.delete(stock)
    redirect_to my_portfolio_path, notice: 'Stock was successfully deleted.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @user_stocks = current_user.stocks.alphabetical
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FinanceTracker" %></title>
    
    <%= csrf_meta_tags %>
  
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css",
      media: 'all' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">FinanceTracker</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
      <footer>
        <p>&copy; Company 2020</p>
      </footer>
    </div> <!-- /container -->
  </body>
</html>

app/views/stocks/_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Current Price</th>
      <% if @user == current_user %>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @user_stocks.each do |stock| %>
      <tr>
        <td><%= stock.name %></td>
        <td><%= stock.ticker %></td>
        <td><%= stock.last_price %></td>
        <% if @user == current_user %>
          <td>
            <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe,
              user_stock_path(stock),method: :delete, class: 'badge badge-danger', 
              data: { confirm: ' Are you sure?'} %>
          </td>
        <% end %>
      </tr>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td><strong>showing:</strong></td>
      <td><%= @user_stocks.size %></td>
    </tr>
  </tbody>
</table>

app/views/users/_result.html.erb
<% if params[:action] == 'search' %>
  <div class="result-block">
    <%= bootstrap_flash %>
  </div>
<% end %>

<% if @stock %>
  <div class="well results-block">
    <strong>Symbol: </strong><%= @stock.ticker %>
    <strong>Name: </strong><%= @stock.name %>
    <strong>Price: </strong><%= @stock.last_price %>
    <% if current_user.can_add_stock?(@stock.ticker) %>
      <%= link_to 'Add to my stocks', user_stocks_path(user: current_user, stock_ticker: @stock.ticker),
        class: 'btn btn-xs btn-success', method: :post %>
    <% else %>
      <span class="label label-default">
        Stock cannot be added  because you have already added
        <% if !current_user.under_stock_limit? %>
          10 Stocks.
        <% else %>
          this stock.
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
$('#results').html("<%= j(render 'users/result.html') %>")

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<h3>Search for Stocks</h3>

<div id="stock-lookup">
  <%= form_tag search_stocks_path, remote: true, method: :get, id: 'stock-lookup-form' do %>
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-10">
        <%= text_field_tag :stock, params[:stock], placeholder: 'Stock Ticker Symbol',
          autofocus: true, class: 'form-control search-box input-lg' %>
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: 'btn btn-lg btn-success') do %>
          <i class="fa fa-search"></i> Look up a Stock
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="results">
  <%= render 'result' %>
</div>

<% unless current_user.stocks.empty? %>
  <h3>Your Stocks:</h3>

  <%= render 'stocks/list' %>
<% end %>

app/views/welcomes/index.html.erb
<h1>Welcome to Finance Tracker</h1>

<%= link_to 'Logout', destroy_user_session_path, method: :delete %>